### ISSUE TITLE
Where should sicp go?

### ISSUE THREAD

**Issue by martin-henz** [source-academy/docs#3]
It may be good to place the textbook into source-academy, as:

source-academy / sicp

What do you all think?

**Comment by indocomsoft** [comment]
Yeah I think it's a good idea to put the repo here

**Comment by remo5000** [comment]
I personally feel like SICP should have its own repository, as it is used more as an educational resource than as documentation, but hosting it here is reasonable enough :+1:

**Comment by martin-henz** [comment]
Actually, github terminology is that "source-academy" is the "organization" and "cadet" and "sicp" are "repositories".

**Comment by martin-henz** [comment]
Each "repository" should have its own "docs" folder. There could be a "docs" folder in the "organization" in order to describe how the different repositories hang together.
